### ISSUE TITLE
Reference in new issue　テスト

### ISSUE THREAD

**Issue by Kosuke953** [TakeoIshida/gs_schedule#2]
javascript復習　完了　1月19日
PHP開発環境設定完了　1月20日

_Originally posted by @TakeoIshida in https://github.com/TakeoIshida/gs_schedule/issues/1#issuecomment-1016998202_

Reference in new issueのテストです！

**Comment by TakeoIshida** [comment]
・監督のgitにアクセスしてコメント投稿練習。
・ドットインストールでgit hub学習。

**Comment by IttetsuSato** [comment]
Nice issue!
👍
